### ISSUE TITLE
Use Promises as an alternative to callbacks

### ISSUE THREAD

**Issue by Alexis-De-La-Torre** [ericblade/mws-simple#21]
I just started a project that can will use this library a lot but it uses Promises and not callbacks.
I will get to work on making it the library return a Promise when no Callback is given.

**Comment by ericblade** [comment]
great! :) i've already messed with the internals of this quite a bit since I forked it, I didn't want to do a lot of work to re-do more of it, since it's easy enough to just wrap it in a promisify wrapper.  I'd be happy to entertain a pull req, though.

**Comment by ericblade** [comment]
@Alexis-De-La-Torre I just got a bit bored, couldn't sleep, and decided to extend it out to 150 lines, clean up the organization, make it a lot more readable.  Check out v3, and you shouldn't have any problem with making it use Promises. :-)

**Comment by avrtau** [comment]
@ericblade I have made a pull request that adds Promise to the `request` method.

**Comment by ericblade** [comment]
this has been merged, thanks @avrtau
